language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: IroFrW2s5aIGsb0eBYt6tMs7QF9prRrrNjjefoXIhbAOH4naag/OmKGe/+5gNScbCXGPhNg92ZnzgHuqGZDrMad1lWd5fiWyaZhpitW5fw8HHQwSKrTyRUGOrGdE+R3r+6PET6JE9kHDcH1OuoOCPWZcOhM+U230jqsFWpkUl+xu9VLgxRGM8+0SfgQLrogBCKmdz+rixqx7kF9vRdUBzhAckbD/VkWl3BHGyBwSbCAZPBOEWhTubCJsqFqa8bNEpQe7J6wX4pwFttwGE83wJRPcl+uI4mX400WFvBtlnXcJ//LuGAGT+Z8LfKGjMXzaMnHrmVkjcE3p5X4SgsbPFBH0vd6ZufAcRTCuNXnxXNe92jRWs90AMjCvsSgHuirbn7KJkSPw2w703f5zYOTLOiXzjTn91h8c9GE67VuDW+qJ3xiGuoWxmlFc6LmfsTYJJlHjzOSM+0nHUinjlvcvWneXfJDYUbEH/dqEjkbrMHac61mfdPDC6O/Q36+HLtHaOAro3nj2X2pq/IQ2UwO8Egmm2t5aQz3D97I4f3cBHWsVjmx/nx+oxAlFIwYt8Vy3ANM0QkLK0CKqgCPtsvpsupR8nEaPDi3HOj8BLqlEeAslAeVUyPushe40/VlqtPKYoaYuCk4PnM3ubChSFA0FonCbOPik1PvLWegZGG0k8j8=
