language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_deploy:
  - now rm node-cd --token $NOW_TOKEN --yes || true
deploy:
- provider: script
  script: $TRAVIS_BUILD_DIR/deploy.sh
  skip_cleanup: true
  on:
    master: true
