language: node_js
node_js:
- node
cache:
  directories:
  - "$HOME/.npm"
addons:
  ssh_known_hosts:
  - 43.240.97.67
before_install:
- openssl aes-256-cbc -K $encrypted_adf042f75aba_key -iv $encrypted_adf042f75aba_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d

install:
  - echo 'YNueDF+nkVnKHEIWrFIkbRL4PrQ=|SHB25moitrmb3yxRhq186XkZ/T0= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' $HOME/.ssh/known_hosts

before_deploy:
- npm run test:unit
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  global:
  - VUE_APP_EES_TILES_API=https://ees-server.now.sh
  - secure: IroFrW2s5aIGsb0eBYt6tMs7QF9prRrrNjjefoXIhbAOH4naag/OmKGe/+5gNScbCXGPhNg92ZnzgHuqGZDrMad1lWd5fiWyaZhpitW5fw8HHQwSKrTyRUGOrGdE+R3r+6PET6JE9kHDcH1OuoOCPWZcOhM+U230jqsFWpkUl+xu9VLgxRGM8+0SfgQLrogBCKmdz+rixqx7kF9vRdUBzhAckbD/VkWl3BHGyBwSbCAZPBOEWhTubCJsqFqa8bNEpQe7J6wX4pwFttwGE83wJRPcl+uI4mX400WFvBtlnXcJ//LuGAGT+Z8LfKGjMXzaMnHrmVkjcE3p5X4SgsbPFBH0vd6ZufAcRTCuNXnxXNe92jRWs90AMjCvsSgHuirbn7KJkSPw2w703f5zYOTLOiXzjTn91h8c9GE67VuDW+qJ3xiGuoWxmlFc6LmfsTYJJlHjzOSM+0nHUinjlvcvWneXfJDYUbEH/dqEjkbrMHac61mfdPDC6O/Q36+HLtHaOAro3nj2X2pq/IQ2UwO8Egmm2t5aQz3D97I4f3cBHWsVjmx/nx+oxAlFIwYt8Vy3ANM0QkLK0CKqgCPtsvpsupR8nEaPDi3HOj8BLqlEeAslAeVUyPushe40/VlqtPKYoaYuCk4PnM3ubChSFA0FonCbOPik1PvLWegZGG0k8j8=
after_success:
- bash .travis/deploy.sh
